[package]
name = "tidy"
version = "0.1.0"
edition = "2021"
autobins = false

[dependencies]
cargo_metadata = "0.14"
regex = "1"
serde_json = "1"
# NOTE: intentionally doesn't use the in-tree rustdoc-json-types so that we're resiliant to breaking
# changes between beta and nightly (since tidy always uses stage 0 rustdoc).
rustdoc-types = "0.18"
syn = { version = "1", features = ["full"] }
lazy_static = "1"
walkdir = "2"

[[bin]]
name = "rust-tidy"
path = "src/main.rs"
